### ISSUE TITLE
Read and comment before Monday June 7

### ISSUE THREAD

**Issue by iangrooms** [ocean-eddy-cpt/gcm-filters-paper#41]
The revisions are complete and ready for your perusal. I will send all documents in a separate email to the authors. **Please either comment about needed changes, or just give this comment a thumbs-up to indicate that no changes are needed.** Please get comments in before Monday June 7.

**Comment by rabernat** [comment]
I have read the revision and reply. Amazing job and such a quick turnaround. I love the new figures. I'm so impressed by this team... 🚀

**Comment by iangrooms** [comment]
@arthurBarthe Can you give me an OK to go ahead with these revisions?
